import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { AnimateOnScrollDirective } from '../../shared/animate-on-scroll.directive';

@Component({
  selector: 'app-neetcode-features',
  standalone: true,
  imports: [CommonModule, AnimateOnScrollDirective],
  template: `
    <section class="relative py-24 md:py-32 overflow-hidden transition-colors duration-500" [ngClass]="dark ? 'bg-[#0a0a0c]' : 'bg-[#fafafa]'">
      <div class="pointer-events-none absolute inset-0" [style.background]="dark ? 'radial-gradient(ellipse at 50% 0%, rgba(99,102,241,0.03) 0%, transparent 50%)' : 'radial-gradient(ellipse at 50% 0%, rgba(99,102,241,0.02) 0%, transparent 50%)'"></div>
      <div class="relative z-10 max-w-6xl mx-auto px-6 md:px-8">
        <p appAnimateOnScroll class="text-xs font-semibold tracking-[0.2em] uppercase text-center mb-4 opacity-0 [&.is-visible]:animate-fade-up" [ngClass]="dark ? 'text-[#6366f1]' : 'text-[#4f46e5]'">WHY NEETCODE</p>
        <h2 appAnimateOnScroll [animationDelay]="60" class="text-3xl md:text-5xl font-bold text-center tracking-tight opacity-0 [&.is-visible]:animate-fade-up" [ngClass]="dark ? 'text-[#e4e4e7]' : 'text-[#09090b]'">Built different</h2>
        <p appAnimateOnScroll [animationDelay]="120" class="text-center text-base md:text-lg mt-4 mb-16 max-w-lg mx-auto opacity-0 [&.is-visible]:animate-fade-up" [ngClass]="dark ? 'text-[#52525b]' : 'text-[#71717a]'">Everything you need to land your dream job. Nothing you don't.</p>
        <div class="grid grid-cols-1 md:grid-cols-5 gap-4 mb-4">
          <div appAnimateOnScroll class="bento-card group md:col-span-3 relative rounded-2xl p-8 overflow-hidden opacity-0 [&.is-visible]:animate-fade-up" [ngClass]="dark ? 'bg-[#111113] border border-white/[0.04] hover:border-[#6366f1]/20' : 'bg-white border border-black/[0.04] hover:border-[#4f46e5]/15'">
            <div class="pointer-events-none absolute -top-20 -right-20 w-64 h-64 rounded-full opacity-0 group-hover:opacity-100 transition-opacity duration-700" [style.background]="dark ? 'radial-gradient(circle, rgba(99,102,241,0.08) 0%, transparent 60%)' : 'radial-gradient(circle, rgba(79,70,229,0.05) 0%, transparent 60%)'" style="filter: blur(50px)"></div>
            <div class="relative z-10"><div class="inline-flex items-center gap-2 text-xs font-semibold tracking-wider uppercase mb-4 px-3 py-1.5 rounded-full" [ngClass]="dark ? 'bg-[#6366f1]/10 text-[#818cf8]' : 'bg-[#4f46e5]/5 text-[#4f46e5]'">🗺️ Roadmaps</div><h3 class="text-xl md:text-2xl font-bold mb-2" [ngClass]="dark ? 'text-[#e4e4e7]' : 'text-[#09090b]'">Follow the optimal path</h3><p class="text-sm max-w-sm mb-8" [ngClass]="dark ? 'text-[#52525b]' : 'text-[#71717a]'">Visual roadmaps guide you through topics in the right order. Never wonder what to study next.</p></div>
            <div class="relative z-10 flex items-center gap-3 flex-wrap"><ng-container *ngFor="let topic of ['Arrays', 'Two Pointers', 'Stack', 'Binary Search', 'Trees', 'Graphs', 'DP']; let i = index"><div class="flex items-center gap-2"><div class="flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium transition-all duration-300" [ngClass]="i < 3 ? (dark ? 'bg-neet-easy/10 text-neet-easy border border-neet-easy/20' : 'bg-green-50 text-green-600 border border-green-200') : i < 5 ? (dark ? 'bg-[#6366f1]/10 text-[#818cf8] border border-[#6366f1]/20' : 'bg-indigo-50 text-indigo-600 border border-indigo-200') : (dark ? 'bg-white/[0.03] text-[#52525b] border border-white/[0.06]' : 'bg-gray-50 text-[#71717a] border border-black/[0.06]')"><span class="w-1.5 h-1.5 rounded-full" [ngClass]="i < 3 ? 'bg-neet-easy' : i < 5 ? 'bg-[#6366f1]' : (dark ? 'bg-[#3f3f46]' : 'bg-[#d4d4d8]')"></span>{{ topic }}</div><svg *ngIf="i < 6" class="w-4 h-4 opacity-20" [ngClass]="dark ? 'text-white' : 'text-black'" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg></div></ng-container></div>
          </div>
          <div appAnimateOnScroll [animationDelay]="120" class="bento-card group md:col-span-2 relative rounded-2xl p-8 overflow-hidden opacity-0 [&.is-visible]:animate-fade-up" [ngClass]="dark ? 'bg-[#111113] border border-white/[0.04] hover:border-[#6366f1]/20' : 'bg-white border border-black/[0.04] hover:border-[#4f46e5]/15'">
            <div class="pointer-events-none absolute -bottom-16 -right-16 w-48 h-48 rounded-full opacity-0 group-hover:opacity-100 transition-opacity duration-700" [style.background]="dark ? 'radial-gradient(circle, rgba(139,92,246,0.08) 0%, transparent 60%)' : 'radial-gradient(circle, rgba(139,92,246,0.05) 0%, transparent 60%)'" style="filter: blur(40px)"></div>
            <div class="relative z-10"><div class="inline-flex items-center gap-2 text-xs font-semibold tracking-wider uppercase mb-4 px-3 py-1.5 rounded-full" [ngClass]="dark ? 'bg-[#8b5cf6]/10 text-[#a78bfa]' : 'bg-purple-50 text-purple-600'">🧩 Patterns</div><h3 class="text-xl font-bold mb-2" [ngClass]="dark ? 'text-[#e4e4e7]' : 'text-[#09090b]'">15 core patterns</h3><p class="text-sm mb-6" [ngClass]="dark ? 'text-[#52525b]' : 'text-[#71717a]'">Cover 90% of interview questions by mastering recurring patterns.</p></div>
            <div class="relative z-10 space-y-2"><ng-container *ngFor="let pat of ['Sliding Window', 'Two Pointers', 'Fast & Slow', 'Merge Intervals', 'Cyclic Sort']; let j = index"><div class="flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-mono transition-all duration-300" [style.opacity]="1 - j * 0.12" [ngClass]="dark ? 'bg-white/[0.03] text-[#a1a1aa]' : 'bg-black/[0.02] text-[#52525b]'"><span class="text-[10px] font-bold w-4" [ngClass]="dark ? 'text-[#6366f1]' : 'text-[#4f46e5]'">{{ j + 1 }}</span>{{ pat }}</div></ng-container></div>
          </div>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div appAnimateOnScroll [animationDelay]="200" class="bento-card group relative rounded-2xl p-8 overflow-hidden opacity-0 [&.is-visible]:animate-fade-up" [ngClass]="dark ? 'bg-[#111113] border border-white/[0.04] hover:border-[#6366f1]/20' : 'bg-white border border-black/[0.04] hover:border-[#4f46e5]/15'"><div class="relative z-10"><div class="w-14 h-14 rounded-2xl flex items-center justify-center mb-5 transition-transform duration-300 group-hover:scale-110" [ngClass]="dark ? 'bg-red-500/10' : 'bg-red-50'"><svg class="w-6 h-6 text-red-500" viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"/></svg></div><h3 class="text-lg font-bold mb-2" [ngClass]="dark ? 'text-[#e4e4e7]' : 'text-[#09090b]'">Video walkthroughs</h3><p class="text-sm" [ngClass]="dark ? 'text-[#52525b]' : 'text-[#71717a]'">Every problem explained step-by-step with intuition, approach, and code.</p></div></div>
          <div appAnimateOnScroll [animationDelay]="280" class="bento-card group relative rounded-2xl p-8 overflow-hidden opacity-0 [&.is-visible]:animate-fade-up" [ngClass]="dark ? 'bg-[#111113] border border-white/[0.04] hover:border-[#6366f1]/20' : 'bg-white border border-black/[0.04] hover:border-[#4f46e5]/15'"><div class="relative z-10"><div class="mb-5"><div class="text-3xl font-bold mb-1" [ngClass]="dark ? 'text-[#e4e4e7]' : 'text-[#09090b]'">73<span class="text-lg" [ngClass]="dark ? 'text-[#6366f1]' : 'text-[#4f46e5]'">/150</span></div><div class="w-full h-1.5 rounded-full mt-2" [ngClass]="dark ? 'bg-white/[0.04]' : 'bg-black/[0.04]'"><div class="h-full rounded-full transition-all duration-700" style="width: 48.6%" [ngClass]="dark ? 'bg-[#6366f1]' : 'bg-[#4f46e5]'"></div></div></div><h3 class="text-lg font-bold mb-2" [ngClass]="dark ? 'text-[#e4e4e7]' : 'text-[#09090b]'">Track everything</h3><p class="text-sm" [ngClass]="dark ? 'text-[#52525b]' : 'text-[#71717a]'">See your strengths and gaps. Know exactly where you stand.</p></div></div>
          <div appAnimateOnScroll [animationDelay]="360" class="bento-card group relative rounded-2xl p-8 overflow-hidden opacity-0 [&.is-visible]:animate-fade-up" [ngClass]="dark ? 'bg-[#111113] border border-white/[0.04] hover:border-[#6366f1]/20' : 'bg-white border border-black/[0.04] hover:border-[#4f46e5]/15'"><div class="relative z-10"><div class="mb-5 font-mono text-[11px] leading-relaxed p-3 rounded-lg" [ngClass]="dark ? 'bg-white/[0.02] text-[#a1a1aa]' : 'bg-black/[0.02] text-[#52525b]'"><span [ngClass]="dark ? 'text-[#c084fc]' : 'text-purple-600'">def</span> <span [ngClass]="dark ? 'text-[#818cf8]' : 'text-indigo-600'">twoSum</span>(nums, target):<br>&nbsp;&nbsp;seen = {{ '{' }}{{ '}' }}<br>&nbsp;&nbsp;<span [ngClass]="dark ? 'text-[#c084fc]' : 'text-purple-600'">for</span> i, n <span [ngClass]="dark ? 'text-[#c084fc]' : 'text-purple-600'">in</span> <span [ngClass]="dark ? 'text-[#818cf8]' : 'text-indigo-600'">enumerate</span>(nums):<br>&nbsp;&nbsp;&nbsp;&nbsp;<span [ngClass]="dark ? 'text-[#c084fc]' : 'text-purple-600'">if</span> target-n <span [ngClass]="dark ? 'text-[#c084fc]' : 'text-purple-600'">in</span> seen:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span [ngClass]="dark ? 'text-[#c084fc]' : 'text-purple-600'">return</span> <span [ngClass]="dark ? 'text-neet-easy' : 'text-green-600'">✓</span></div><h3 class="text-lg font-bold mb-2" [ngClass]="dark ? 'text-[#e4e4e7]' : 'text-[#09090b]'">Built-in editor</h3><p class="text-sm" [ngClass]="dark ? 'text-[#52525b]' : 'text-[#71717a]'">Write, run, and test solutions in 10+ languages. Right in your browser.</p></div></div>
        </div>
      </div>
    </section>
  `,
})
export class NeetcodeFeaturesComponent {
  @Input() dark = true;
}
